apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: globex-prod-
resources:
  - ../../base
components:
  - ../../components/tenants/globex
  - ../../components/envs/prod
patches:
  - path: patch-db.yaml
    target:
      kind: Deployment
      name: checkout-web
